server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/my?&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 182008
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.cloudproviderpayment8001.Entities   # 所有Entity别名类所在包

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
      #单机版只注册一个服务注册中心
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001 #添加此处
    prefer-ip-address: true #添加此处
      #心跳检测与续约时间
      #开发时没置小些，保证服务关闭后注册中心能即使剔除服务
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
      #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2